version: '3.8'

services:
  web:
    build: ./ebooksapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ebooksapi/:/usr/src/ebooksapi/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=drf2_user
      - POSTGRES_PASSWORD=drf2_pass
      - POSTGRES_DB=drf2_db
    ports:
      - "5433:5432"

volumes:
  postgres_data:  